### ISSUE TITLE
Doesn't read NUXT_HOST from .env file

### ISSUE THREAD

**Issue by BulgarianHealer** [nuxt/cli#100]
### Environment

Nuxt project info:                                                                                                                                 3:00:18 PM

------------------------------
- Operating System: Linux
- Node Version:     v18.15.0
- Nuxt Version:     3.7.0
- CLI Version:      3.7.0
- Nitro Version:    2.6.1
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      ssr, nitro, modules, components, css, vite, runtimeConfig, googleFonts, colorMode, image
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.1, @nuxtjs/google-fonts@3.0.2, @nuxtjs/color-mode@3.3.0, @nuxt/image@1.0.0-rc.1
- Build Modules:    -
------------------------------

### Reproduction

https://codesandbox.io/p/sandbox/nuxtjs-3-7-0-gt3sj6?file=/app.vue:1,1

### Describe the bug

After update to the latest version 3.7.0, after i run npm run dev, i saw that it doesn't run on the host from .env file.

I have tried with several ways like HOST, NITRO_HOST in the package.json file but it doesn't want to work.
I have tried with removing .nuxt folder and node_modules but still the same, on the reproduction i dont think that it will work, because there is no interface with that ip at all.

**Comment by pi0** [comment]
Let's track via https://github.com/nuxt/cli/issues/99

**Comment by george-martinec** [comment]
same

**Comment by pi0** [comment]
Sorry for the inconvenience. Several fixes were added to [nuxi 3.7.2](https://github.com/nuxt/cli/releases/tag/v3.7.2) in order to address this issue.

You can self-update using `npx nuxi upgrade --force` and make sure to use 3.7.2+ using `npx nuxi info`. 

If you still having issues, don't hesitate to ping me.

**Comment by BulgarianHealer** [comment]
Thanks, now it working.

I have a question, so with the bug i had to add --host to expose the local and wan ip address, also i got an QR code, without it was listening on localhost only, is there a way to disable expose the local/wan ip or remove the QR code now?

I'm running npm run dev (nuxt dev) without any options.
@pi0

**Comment by pi0** [comment]
You can use `--host 127.0.0.1` (or IP of your desired loopback/NIC) to avoid exposing to wan and `--no-qr` to disable displaying QR code when IP is exposed.
