### ISSUE TITLE
WebSocket Support 

### ISSUE THREAD

**Issue by pi0** [nuxt/cli#108]
[description is wip]

Since Nuxt 3, we had (semi-official) solutions to support WebSocket in development and production but never a standard layer. This had been something we planned to support universally in nuxt/nitro dev server and runtime.

With the introduction of new dev server CLI architecture in nuxi 3.7 (#81) some of the current solutions stooped to be working.

My plan is to first make sure there is a basic replacement for current solutions and then put the stable WS layer on fast track to finally resolve this. (Update: hooking to the server `upgrade` via `listen` should work again now via https://github.com/nuxt/cli/pull/127)

Related issues:
- #101
- #107
- #112

**Comment by mumi** [comment]
Any update on this?

**Comment by BghinC** [comment]
> Any update on this?

We just got an update yesterday. You can learn more about it here: https://twitter.com/_pi0_/status/1761875980849713261

**Comment by pi0** [comment]
Experimental websocket is available in nightly channels. 

See https://github.com/pi0/nuxt-websocket

**Comment by pi0** [comment]
CLI support landing: https://github.com/nuxt/cli/pull/348

Note: Some features such as supporting `devHandlers` are not complete yet and need progress on Nitro side. You can track via https://nitro.unjs.io/guide/websocket and https://github.com/unjs/nitro/issues/2171
