### ISSUE TITLE
`nuxi start` missing as a part of command cli in v3.7

### ISSUE THREAD

**Issue by Q16solver** [nuxt/cli#113]
In the previous versions of nuxt, I was using `nuxt start` to start my production server, though I did later find out it's just an alias to `nuxt preview` after looking at the source code. It is convenient to have this alias though, could we add this back?

**Comment by pi0** [comment]
I would recommend the same but this is a breaking change and i believe we should keep alias with a warning till next major version.

**Comment by Q16solver** [comment]
Sure, that makes sense, but normally “start” has conventionally meant starting a production server afaik, perhaps it can just be an alias to node .server…

**Comment by danielroe** [comment]
Yes, it does just run that command, alongside loading `.env` and a couple other things. The issue is that then you still have to have `nuxi` itself installed.

**Comment by LuXDAmore** [comment]
@danielroe What about the SPA building?

> You can preview this build using npx serve src/.output/public
> HTML content not prerendered because ssr: false was set

We can't run the command `node src/.output/server/index.mjs`

I think `nuxi start` could be useful also for this use case:
one command to make it more clear and easy to run. No?

**Comment by pi0** [comment]
I am probably speaking ahead of myself and our plans but yes, there might be benefits of supporting (standalone) `nuxi` binary for production deployment lunching. 

It is currently not intended to be and we might end up having something more compact for that (as part of nitro self-hosting deployment bundle improvement plans). 

For now, please consider directly uploading `.output` directory to your production environments and not rely on main project (dev) dependencies and `start` command.

**Comment by LuXDAmore** [comment]
> For now, please consider directly uploading .output directory to your production environments and not rely on main project (dev) dependencies and start command.

@pi0 In our project we're using `nuxi start ./src` to run some _e2e test_ on the local machine with _Playwright_, so it's very useful.


Now i've fixed it with:
- `"start": "npx serve src/.output/public"  // package.json`
- `{ webServer: { command: 'yarn start' } } // playwright.config`

but like this we need to have installed **npx** globally (i know it's installed by default but with the command `nuxi start` everything was already "inside" the project with npm/yarn).

Just, having one command to manage both ssr and spa modes it's also something i can bring on every project.

> I am probably speaking ahead of myself and our plans

But yes ok, i can understand your plans 😄

**Comment by pi0** [comment]
Thanks for sharing your usecases @LuXDAmore it definitely helps to make decition about start command 👍🏼

**Comment by danielroe** [comment]
It was a mistake and has already been reverted.

**Comment by danielroe** [comment]
It is. You can already try it out with `nuxi-edge`, before a formal release.
