### ISSUE TITLE
3.7.0 - net::ERR_CONNECTION_RESET 200 [WSL2, Docker]

### ISSUE THREAD

**Issue by or2e** [nuxt/cli#118]
### Environment

- Operating System: Linux
- Node Version:     v18.17.0
- Nuxt Version:     3.7.0
- Nitro Version:    2.6.2
- Package Manager:  pnpm@8.7.0
- Builder:          vite

### Reproduction

I can't figure out exactly what's wrong yet, I'll try to disable custom modules and plugins, but it's probably not the problem.
Possibly similar issue: https://github.com/vitejs/vite/issues/14190

### Describe the bug

<details>
  <summary>Nuxt 3.7.0</summary>

  https://github.com/nuxt/nuxt/assets/33551334/1d07a86f-a4bc-4cb6-a779-536adff3092e
</details>

<details>
  <summary>Nuxt 3.6.5</summary>

  https://github.com/nuxt/nuxt/assets/33551334/68b6a967-dab7-4a1d-9a23-34d2ed27117f
</details>

**Comment by pi0** [comment]
Thanks. Moving to CLI to keep track.

**Comment by pi0** [comment]
Hi @or2e . Can you please try with latest [3.7.3](https://github.com/nuxt/cli/releases/tag/v3.7.3) if can still reproduce?

**Comment by or2e** [comment]
@pi0 hi ;)

Sadly, I can't confirm the fix. The problem continues to occur
<details>
  <summary>env</summary>

  ![image](https://github.com/nuxt/cli/assets/33551334/5f4e6b83-050d-403e-8449-e25c68b66ed4)
  
```
Operating System: Linux
Node Version:     v18.17.0
Nuxt Version:     3.7.0
CLI Version:      3.7.3
Nitro Version:    2.6.2
Package Manager:  pnpm@8.7.0
```
</details>

**Comment by or2e** [comment]
this recipe https://github.com/nuxt/nuxt/discussions/22823#discussioncomment-6840605 didn't work for me.

**Comment by dosstx** [comment]
Spent a few days trying to debug this and even searched the issues here and did not see it until someone specifically linked this page for me. Thanks for the heads up! I confirm that simply changing from `localhost:3000` to `127.0.0.1:3000` is the fix for me.

Heck, Nuxt even suggests that as the local host when u see the CLI:

```
Nuxt 3.7.1 with Nitro 2.6.3                                                                                                                                   
  ➜ Local:    http://127.0.0.1:3000/   //<-----------------
  ➜ Network:  use --host to expose
  ```

**Comment by or2e** [comment]
@dosstx 
It didn't work for me.
`npx nuxi dev --host 127.0.0.1`

**Comment by or2e** [comment]
keep track https://github.com/nuxt/cli/issues/118

**Comment by pi0** [comment]
@or2e can you please try `npx nuxi-edge@latest dev` on your env to see if it resolves your issue?

**Comment by or2e** [comment]
@pi0 gladly!
<details>
  <summary>Details</summary>
  
  ![image](https://github.com/nuxt/cli/assets/33551334/481a5c20-2f66-4528-bd0c-9c93df157781)
</details>

**Comment by or2e** [comment]
> @pi0 gladly!
> 
> Details
> ![image](https://user-images.githubusercontent.com/33551334/268098001-481a5c20-2f66-4528-bd0c-9c93df157781.png)

I mean, the problem remains.
if needed, I can provide an environment (discord, AnyDesk)

**Comment by pi0** [comment]
Feel free to DM me in discord (pi0).

**Comment by Manusan42** [comment]
I have the same setup with the same problem. Using VSCode with devcontainer (Windows 10 - WSL2).
I have nuxt 3.7.4 and also tried `npx nuxi-edge@latest dev`. 
I often get (sometimes multiple) `net::ERR_CONTENT_LENGTH_MISMATCH 200` of random css/js/woff2 resources.

Is there any new information about this? I just started with nuxt/vue and it's a bit frustrating.

**Comment by or2e** [comment]
@Manusan42 
https://github.com/nuxt/cli/issues/181
