### ISSUE TITLE
Command `nuxi dev ./src -o` is not opening in the browser

### ISSUE THREAD

**Issue by LuXDAmore** [nuxt/cli#125]
### Environment
Nuxt 3.7

### Reproduction
Nuxt 3.7

### Describe the bug
Before upgrading to nuxt@3.7 the command `nuxi dev ./src -o` was opening a new browser window/tab on `localhost:3000`, now its' not.

#### Additional notes
From the [documentation](https://nuxt.com/docs/api/commands/dev)
> --open, -o | false | Open URL in browser.

**Comment by pi0** [comment]
Are you on Windows or WSL?

**Comment by LuXDAmore** [comment]
@pi0 I'm on the [Windows terminal](https://www.microsoft.com/store/productid/9N0DX20HK701?ocid=pdpshare) app.

**Comment by pi0** [comment]
Thanks for the notice. there was a regression with `-o` arg handling it should be fixed in `nuxi-edge` and next release of `nuxi`.

**Comment by pi0** [comment]
Fix is released in [v3.7.3](https://github.com/nuxt/cli/releases/tag/v3.7.3).
