### ISSUE TITLE
improve error handling experience for `nuxi module add` when install fails

### ISSUE THREAD

**Issue by Atinux** [nuxt/cli#131]
Example of installing an npm package that does not exist:
![CleanShot 2023-08-31 at 11.57.49@2x.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2023_08_31_at_11_57_49_2x_64ef9630a4.png)

**Comment by pi0** [comment]
It would be nice to indeed improve the error handling but there might be other reasons (such as network error or private packages or package manager fault) that packages cannot be installed. I suggest to instead, use a confirmation prompt either continuing the addition to the config or cancel operation when install is failing.

**Comment by pi0** [comment]
Also likning https://github.com/unjs/nypm/issues/89, i am thinking when package manager cannot be detected, to also make nypm behavior more "gentle" and only update `package.json` (using manual npm resolution to make sure package is still valid)
