### ISSUE TITLE
Nuxt 3 install issues

### ISSUE THREAD

**Issue by Norbert-Brett** [nuxt/cli#132]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.5.0
- Nuxt Version:     -
- CLI Version:      3.7.3
- Nitro Version:    -
- Package Manager:  unknown
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

`npx nuxi@latest init fit-app`

✔ Which package manager would you like to use?
`yarn`
◐ Installing dependencies...                                                                                  

 ERROR  Error: Command failed with ENOENT: corepack yarn install                                           
spawn corepack ENOENT

### Describe the bug

I was trying to install Nuxt 3 using `pnpm` or `yarn`, but for some reason I kept having the following  issue:

`pnpm dlx nuxi@latest init fit-app`

Packages: +2
++
Progress: resolved 2, reused 1, downloaded 1, added 2, done

✔ Which package manager would you like to use?
`pnpm`
◐ Installing dependencies...                                                                                    13:56:48

 ERROR  Error: Command failed with ENOENT: corepack pnpm install                                                13:56:48
spawn corepack ENOENT

or

`npx nuxi@latest init fit-app`

✔ Which package manager would you like to use?
`yarn`
◐ Installing dependencies...                                                                                    13:58:54

 ERROR  Error: Command failed with ENOENT: corepack yarn install                                                13:58:54
spawn corepack ENOENT

The only package manager working was 'npm'

**Comment by Norbert-Brett** [comment]
It only works if you use Corepack installed. Another workaround, if you don't want Corepack installed, is to manually install it from within that folder after the error prompt.

**Comment by pi0** [comment]
Latest version of nuxi (3.8.2) has a fallback mechanism when corepack is not available. Let me know if still experiencing issues to investigate.
