### ISSUE TITLE
Nuxt 3.7.0 11 times slower

### ISSUE THREAD

**Issue by vladimir-pankov** [nuxt/cli#138]
Nuxt 3.7.0 with Nitro 2.6.2 generates 11 times slower
on the same content:

```
nuxi generate
Nuxt 3.7.0 with Nitro 2.6.2
[nitro] ℹ Prerendering 2513 initial routes with crawler
Done in 3457.45s
```
```
nuxi generate
Nuxt 3.6.5 with Nitro 2.6.0
[nitro] ℹ Prerendering 2513 initial routes with crawler
Done in 312.23s.Done in 312.23s.

```
environment: ubuntu 22.04

**Comment by pi0** [comment]
@vladimir-pankov Can you please provide reproduction? 🙏🏼

**Comment by vladimir-pankov** [comment]
I 


@[pi0](https://github.com/pi0)
Thanks for your attention.
I do not have any idea how i could reproduce.
These benchmarks are received on my own live website,
which i can not reproduce anywhere.
During deployment of code i have skipped  _**yarn.lock**_ file and 
`yarn install`
has taken a new version:  Nuxt 3.7.0, which worked very slow ( as You can see above ).  So i have rolled back to previous version nuxt 3.6.5 which works faster. Currently i do not see any problem on my side but i care about future upgrades.
I could attach the proper log files from
`yarn generate 2>&1 > gen.log`
if this can help

**Comment by pi0** [comment]
Feel free to dm me in discord (pi0) so i can help by closely looking at your project.
