### ISSUE TITLE
[v3.8.0] main port is not closed with `nuxi dev`

### ISSUE THREAD

**Issue by pi0** [nuxt/cli#156]
CLI is not always closed

Reproducible in some projects but cannot reproduce stably yet. Investigating.

This will cause to listen to a new port because previous one will be kept used

**Comment by peteromano** [comment]
Following

**Comment by pi0** [comment]
Will be fixed in next release. Previously we were manually trapping sigterm to kill main proxy in reactors it was lost and there was an issue with listhen wasn't doing this.

**Comment by peteromano** [comment]
No 3.7.2 patch?

**Comment by danielroe** [comment]
You can update your nuxi version without Nuxt itself being upgraded. But we do plan a 3.7.2 patch.

**Comment by peteromano** [comment]
Sorry, I just realized this is the cli package 🙂

Ok, nice!

**Comment by schellenbergk** [comment]
how do you update nuxi without updating nuxt?
