### ISSUE TITLE
support http proxy when using `nuxi init` with node >= 18

### ISSUE THREAD

**Issue by ikexing-cn** [nuxt/cli#159]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `0.0.0`
- Nitro Version:    `-`
- Package Manager:  `unknown`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Not exist

### Describe the bug

```
 ERROR  Failed to download template from registry: request to https://raw.githubusercontent.com/nuxt/starter/templates/templates/v3.json failed, reason: connect ECON3

  at /Users/xdclass/.npm/_npx/a95e0f536cf9a537/node_modules/nuxi/dist/chunks/init.mjs:13269:11
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async downloadTemplate (/Users/xdclass/.npm/_npx/a95e0f536cf9a537/node_modules/nuxi/dist/chunks/init.mjs:13268:20)
  at async Object.invoke (/Users/xdclass/.npm/_npx/a95e0f536cf9a537/node_modules/nuxi/dist/chunks/init.mjs:13336:15)
  at async _main (/Users/xdclass/.npm/_npx/a95e0f536cf9a537/node_modules/nuxi/dist/cli.mjs:50:20)
```

### Additional context

` curl https://raw.githubusercontent.com/nuxt/starter/templates/templates/v3.json`
```JSON
{
  "name": "v3",
  "defaultDir": "nuxt-app",
  "url": "https://v3.nuxtjs.org",
  "tar": "https://codeload.github.com/nuxt/starter/tar.gz/refs/heads/v3"
}
```

Everything works fine when I request the URL directly, I think this might be a bug in nuxt.

**Comment by kongxiangyiren** [comment]
> `node -e "require('https').get('https://raw.githubusercontent.com/nuxt/starter/templates/templates/v3.json')"`
> 
> ```
> node:events:491
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: connect ECONNREFUSED 0.0.0.0:443
>     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
> Emitted 'error' event on ClientRequest instance at:
>     at TLSSocket.socketErrorListener (node:_http_client:481:9)
>     at TLSSocket.emit (node:events:513:28)
>     at emitErrorNT (node:internal/streams/destroy:157:8)
>     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
>     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
>   errno: -61,
>   code: 'ECONNREFUSED',
>   syscall: 'connect',
>   address: '0.0.0.0',
>   port: 443
> }
> ```
> 
> It looks like the same error is reported...

If using VPN, try `NODE_TLS_REJECT_UNAUTHORIZED='0' npx nuxi@latest init <project-name>`

**Comment by CNMathon** [comment]
@danielroe So, has it really been solved? I still have this problem, and this issue has been open for more than one year.

**Comment by pi0** [comment]
The main issue is native `fetch` API provided by newer Node.js versions (18+), does not support HTTP agents for proxy support. I am looking for a solution for this.

**Comment by sumasagrp** [comment]
when i do a curl to https://raw.githubusercontent.com/nuxt/starter/templates/templates/v3.json it works

however when i do 

node -e "require('https').get('https://raw.githubusercontent.com/nuxt/starter/templates/templates/v3.json')"

it does not work 

`AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at internalConnectMultiple (node:net:1177:5)
    at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ETIMEDOUT',
  [errors]: [
    Error: connect ETIMEDOUT 185.199.109.133:443
        at createConnectionError (node:net:1634:14)
        at Timeout.internalConnectMultipleTimeout (node:net:1685:38)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -110,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '185.199.109.133',
      port: 443
    },
    Error: connect ENETUNREACH 2606:50c0:8003::154:443 - Local (:::0)
        at internalConnectMultiple (node:net:1176:40)
        at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -101,
      code: 'ENETUNREACH',
      syscall: 'connect',
      address: '2606:50c0:8003::154',
      port: 443
    },
    Error: connect ETIMEDOUT 185.199.108.133:443
        at createConnectionError (node:net:1634:14)
        at Timeout.internalConnectMultipleTimeout (node:net:1685:38)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -110,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '185.199.108.133',
      port: 443
    },
    Error: connect ENETUNREACH 2606:50c0:8002::154:443 - Local (:::0)
        at internalConnectMultiple (node:net:1176:40)
        at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -101,
      code: 'ENETUNREACH',
      syscall: 'connect',
      address: '2606:50c0:8002::154',
      port: 443
    },
    Error: connect ETIMEDOUT 185.199.110.133:443
        at createConnectionError (node:net:1634:14)
        at Timeout.internalConnectMultipleTimeout (node:net:1685:38)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -110,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '185.199.110.133',
      port: 443
    },
    Error: connect ENETUNREACH 2606:50c0:8001::154:443 - Local (:::0)
        at internalConnectMultiple (node:net:1176:40)
        at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -101,
      code: 'ENETUNREACH',
      syscall: 'connect',
      address: '2606:50c0:8001::154',
      port: 443
    },
    Error: connect ETIMEDOUT 185.199.111.133:443
        at createConnectionError (node:net:1634:14)
        at Timeout.internalConnectMultipleTimeout (node:net:1685:38)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -110,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '185.199.111.133',
      port: 443
    },
    Error: connect ENETUNREACH 2606:50c0:8000::154:443 - Local (:::0)
        at internalConnectMultiple (node:net:1176:40)
        at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -101,
      code: 'ENETUNREACH',
      syscall: 'connect',
      address: '2606:50c0:8000::154',
      port: 443
    }
  ]
}`

Seems 

Node.js does not use HTTP_PROXY environment variables. See this discussion https://github.com/nodejs/node/issues/8381.

To set a global Node.js proxy use https://github.com/gajus/global-agent.

I think this is the culprit

**Comment by pi0** [comment]
Fully agree with you @sumasagrp sadly this is a limitation with Node/undici that lacks built-in `HTTP_PROXY` support whereas it is a well-known standard... (also little bit of corporate firewalls that consider "github" as possible harmful resource and block it most of the times)

Sorry for delay on this. this is still on my todo list to find best workaround. Possibly in lowset level (ofetch) to make proxy support for most of our ecosystem out of the box.

**Comment by subinznz** [comment]
Bun seems to have support for http_proxy. Anyways no worries for delay thanks for all your hard work

**Comment by liamwang** [comment]
@codingcn Thanks. 114's DNS works for me. 

BTW, Aliyun's DNS doesn't work, don't try.

**Comment by lzb-libra** [comment]
I have the same issue. Besides the usual settings like changing DNS, modifying the hosts file, and using VPN, I've tried everything, but it still doesn't work.

**Comment by caodaiquang** [comment]
I have same issue :(

**Comment by lzb-libra** [comment]
> I have same issue :(

The best way is actually to give up using it altogether, why hang oneself on one tree? I've already given up.

**Comment by pi0** [comment]
Hi all again and sorry for delay on it. It is really on might schedule and I understand for those behind a firewall, it must be a really hard experience and for that I apologize (I guess on behalf of lazy Node.js team too haha) it is not supported yet 🙏🏼 

I will try to jump at at as soon as possible.

**Comment by hzgotb** [comment]
Powershell:
```powershell
# 请根据实际情况设置梯子地址
$env:all_proxy="ip:port"
$env:FORCE_NODE_FETCH=1
# 最后执行初始化，请根据实际情况执行
pnpm dlx nuxi@latest init equipms
```

Bash
```bash
# 同上，请根据实际情况设置梯子地址和初始化命令
export all_proxy="ip:port" && export FORCE_NODE_FETCH=1 && pnpm dlx nuxi@latest init equipms
```


心路历程：

翻了翻相关的仓库，在 https://github.com/unjs/giget/issues/120 中看到了解决方法

然后捋了一下整个链路
nuxi.init  -> giget.downloadTemplate -> giget.download -> giget.sendFetch -> node-fetch-native.fetch

没有细看 node-fetch-native 的代码，只是稍微看了一下文档，应该是逐渐使用node原生实现的fetch来替代之前的node-fetch方案，并且对不支持原生fetch的旧node版本进行了Polyfill （猜的）。所以在有梯子的情况下还是不生效（貌似原生fetch不接受代理）。
而之前的node-fetch会通过梯子的，那么如上引用的issue所言，通过FORCE_NODE_FETCH来切换到可以用梯子的fetch去下载模板

**Comment by hzgotb** [comment]
Powershell:
```powershell
# 请根据实际情况设置梯子地址
$env:all_proxy="ip:port"
$env:FORCE_NODE_FETCH=1
# 最后执行初始化，请根据实际情况执行
pnpm dlx nuxi@latest init my-app
```

Bash
```bash
# 同上，请根据实际情况设置梯子地址和初始化命令
export all_proxy="ip:port" && export FORCE_NODE_FETCH=1 && pnpm dlx nuxi@latest init my-app
```


心路历程：

翻了翻相关的仓库，在 https://github.com/unjs/giget/issues/120 中看到了解决方法

然后捋了一下整个链路
nuxi.init  -> giget.downloadTemplate -> giget.download -> giget.sendFetch -> node-fetch-native.fetch

没有细看 node-fetch-native 的代码，只是稍微看了一下文档，应该是逐渐使用node原生实现的fetch来替代之前的node-fetch方案，并且对不支持原生fetch的旧node版本进行了Polyfill （猜的）。所以在有梯子的情况下还是不生效（貌似原生fetch不接受代理）。
而之前的node-fetch会通过梯子的，那么如上引用的issue所言，通过FORCE_NODE_FETCH来切换到可以用梯子的fetch去下载模板

**Comment by chunten** [comment]
> 我有同样的问题。除了更改DNS、修改hosts文件、使用VPN等常用设置外，我已经尝试了一切，但仍然不起作用。

me too

**Comment by pi0** [comment]
With latest nuxi, http proxy should be supported out of the box!

**Comment by ricky52529** [comment]
> get ip of raw.githubusercontent.com from a web. and set these into **hosts** file (windows: C:\Windows\System32\drivers\etc) 185.199.111.133 raw.githubusercontent.com rerun 'npx nuxi init nut3-app', and it works

it works~ thank you~

**Comment by Milchreis** [comment]
Hi,

the nightly-build works for `init`. Thank you for the hint, but on `module add` I got the same issue. Could you add the proxy-support for `module`, too?

**Comment by pi0** [comment]
@Milchreis ~> https://github.com/nuxt/cli/issues/419 (this will add proxy support to all internal fetches happening with nuxi CLI)

(however package managers should still also respect and support `http_proxy`)

**Comment by ClungTsang** [comment]
> In china, I succeeded
> 
> Just set DNS 114.114.114.114

it did work ,appreciate

**Comment by Hetari** [comment]
## **Guide: Resolving nuxi init Error: "Failed to download template from registry" on Linux**

### **Steps to Resolve:**

1. **Find the IP Address for `raw.githubusercontent.com`**:
   - Go to [IP Address Lookup](https://www.ipaddress.com/).
   - Search for `raw.githubusercontent.com`.
   - Take note of the current IP address. As of this writing, it could be `185.199.108.133`, but you should verify this for the most up-to-date address.

2. **Edit the `/etc/hosts` File**:
   - Open your terminal.
   - Use the following command to open the `/etc/hosts` file in a text editor with root privileges:
     ```bash
     sudo nano /etc/hosts
     ```
   - Add a new entry for `raw.githubusercontent.com` with the IP address you found. Example:
     ```
     185.199.108.133 raw.githubusercontent.com
     ```
   - Save the file and exit the editor (`Ctrl + O` to save, `Ctrl + X` to exit).

3. **Test the Fix**:
   - Try running the `nuxi init` command again:
     ```bash
     nuxi init <project-name>
     ```
   - It should now successfully download the required template.
![Image](https://github.com/user-attachments/assets/6baf19ef-cf72-48b2-b905-ca8b33ce26f5)
