### ISSUE TITLE
corepack ENOENT pnpm dlx nuxi@latest init

### ISSUE THREAD

**Issue by terion-name** [nuxt/cli#160]
### Environment

Mac OS 13.3.1
pnpm --version 8.4.0
node -v v20.2.0

### Reproduction

just run `pnpm dlx nuxi@latest init project-name`

### Describe the bug

```
pnpm dlx nuxi@latest init project-name
.../Library/pnpm/store/v3/tmp/dlx-1074   |   +2 +
.../Library/pnpm/store/v3/tmp/dlx-1074   | Progress: resolved 2, reused 2, downloaded 0, added 2, done

✔ Which package manager would you like to use?
pnpm
◐ Installing dependencies...                                                                                 12:30:19 PM

 ERROR  Error: Command failed with ENOENT: corepack pnpm install                                             12:30:19 PM
spawn corepack ENOENT
```

**Comment by pi0** [comment]
In latest release (3.8.2) we have added a fallback mechanism when corepack is not installed.  Let me know if still having issues to reopen.

**Comment by aparajita** [comment]
Still happening for me, I had to do `pnpm add -g corepack`.

**Comment by pi0** [comment]
@aparajita can you please confirm this info:

- nuxt cli version
- your method of node.js installation
- os

**Comment by aparajita** [comment]
> [@aparajita](https://github.com/aparajita) can you please confirm this info:
> 
* nuxt cli version: 3.20.0
* your method of node.js installation: pnpm env -g use latest
* os: macOS 14.17.1

**Comment by todpale** [comment]
Happens to me too. 

- Nuxt CLI version: 3.20.0
- Method of node.js installation: pnpm env use -g 22.7.0
- OS: macOS 15.2

Corepack is not installed, just pnpm as a standalone script.

**Comment by aparajita** [comment]
I'm guessing it may have to do with node installed via pnpm.

**Comment by todpale** [comment]
@aparajita no, no connection. I had Node + standalone pnpm, the same error. Then I reinstalled everything with your method, and the same error again. I guess it's because Corepack has been the only solution of using other package managers for a long time, and it could be mentioned in Nuxt codebase.

Anyways, for now, there are two options:
1. Install Corepack
2. Install all dependencies with npm and then reinstall again with pnpm.
