### ISSUE TITLE
Support for choosing package manager on nuxi init command

### ISSUE THREAD

**Issue by lihuelworks** [nuxt/cli#161]
I'm currently using the command `pnpm dlx nuxi@latest init`  as part of a Powershell script to scafoold new projects, but I haven't found in the docs a way to preemptively choose the package manager to avoid seeing this prompt when using `nuxi init`.

![image](https://github.com/nuxt/cli/assets/49965980/6a46081d-58ff-4b82-a2aa-a4b4735583cd)

Am I missing something? If this is already a feature, could it be added to the docs? If not, how can I ask for it to be implemented?

**Comment by danielroe** [comment]
There's a PR in review to do this: https://github.com/nuxt/cli/pull/97

**Comment by lihuelworks** [comment]
Phenomenal Daniel, tysm. No more to comment then.
