### ISSUE TITLE
Nuxi command report error in Linux

### ISSUE THREAD

**Issue by dh336699** [nuxt/cli#179]
### Environment

![image](https://github.com/nuxt/nuxt/assets/32675044/2433480c-3f2b-4025-b214-d5e11daa3a39)

### Reproduction

Just create a new project in Linux

### Describe the bug

When I build my app in Linux, it throws error just like below.
And I tried to create a new project with Nuxt in Linux, it threw error too.
What should I do?

![image](https://github.com/nuxt/nuxt/assets/32675044/25a6a078-4389-49f0-b6a0-feda4b8b93ea)

**Comment by dh336699** [comment]
What should I do bros

**Comment by pi0** [comment]
Can you log also share `cat /etc/issue` and `node --version`? 🙏🏼

**Comment by dh336699** [comment]
> node --version

![image](https://github.com/nuxt/cli/assets/32675044/babe750d-22c6-40e6-8a95-75c45cb59e54)

**Comment by pi0** [comment]
I would recommend you to use Node.js 18. Node 16 is EOL and not supported anymore. (also os version seems not visible but i guess RHEL? kernel is also too old)

**Comment by dh336699** [comment]
> 我您使用 Node.js 18。建议 Node 16 已停产，不再受支持。（操作系统版本似乎不可见，但我猜是 RHEL？内核也太旧了）
@pi0 
![image](https://github.com/nuxt/cli/assets/32675044/987627fa-e420-4f96-b7fc-98d819158ae9)

**Comment by pi0** [comment]
Thanks for sharing it. So yeah both CentOS/RHEL and Node.js versions are outdated. Are you able to update them? 

(feel free to message me in discord `@pi0` would be happy to help on your local environment)

**Comment by dh336699** [comment]
> Thanks for sharing it. So yeah both CentOS/RHEL and Node.js versions are outdated. Are you able to update them?
> 
> (feel free to message me in discord `@pi0` would be happy to help on your local environment)@pi0

In other machine, node version and karnel both same whith it, and that can execute normally

**Comment by dh336699** [comment]
> Thanks for sharing it. So yeah both CentOS/RHEL and Node.js versions are outdated. Are you able to update them?
> 
> (feel free to message me in discord `@pi0` would be happy to help on your local environment)
Thank you @pi0 , according to your suggestion, we had fix it by update node v16.17 => 17.9

**Comment by pi0** [comment]
(Cool! BTW please consider Node.js 18 or 20. 17 is an intermediate release and not stable choice for production)

**Comment by dh336699** [comment]
> (Cool! BTW please consider Node.js 18 or 20. 17 is an intermediate release and not stable choice for production)

Yeah, our OS is too old to support 18, if consider to update 18, need update OS too

**Comment by pi0** [comment]
Just out of curiosity, have you tried https://bun.sh ? You can use it in place of Node.js for production!
