### ISSUE TITLE
Nuxi test does not auto import Vue reactivity?

### ISSUE THREAD

**Issue by arthurbergmz** [nuxt/cli#180]
Hello!

I'm writing some tests for a composable, but keep getting import error from Vue's reactivity:

![image](https://github.com/nuxt/cli/assets/13095084/6c2ffe89-0514-4a96-8fe8-0ecc50495388)

Seems like it is not auto importing like it does when running the app. Was it supposed to be the normal behavior not auto importing in tests but auto import when running the app? Do I have to explicitly import on the composable file to write the tests or is there a way to allow auto imports?

It is possible to reproduce running the tests through "npm test" or "yarn test" in the terminal here: https://codesandbox.io/p/sandbox/sharp-khorana-wv4jfn
![image](https://github.com/nuxt/cli/assets/13095084/8fdab285-0757-40d0-b4af-bd71c7aad014)

Cheers

**Comment by arthurbergmz** [comment]
Seems like I got this working by creating a `vitest.config.ts` with the following content:

```typescript
import AutoImport from 'unplugin-auto-import/vite'

export default {
  plugins: [
    AutoImport({
      imports: ['vue'],
    }),
  ],
}
```

Still, should not the auto import in tests be the default as well? And also auto import composables?

**Comment by danielroe** [comment]
I think you probably want `nuxt-vitest`: https://github.com/danielroe/nuxt-vitest.

**Comment by arthurbergmz** [comment]
> I think you probably want `nuxt-vitest`: https://github.com/danielroe/nuxt-vitest.

That's great, thanks!
