### ISSUE TITLE
`nuxt module add` with shortcut for `@nuxt`

### ISSUE THREAD

**Issue by Atinux** [nuxt/cli#194]
I believe we should be able to run `npx nuxt module add image` as alias of `npx nuxt module add @nuxt/image`

**Comment by pi0** [comment]
I think this is a really nice idea! Following up older RFCs, i think now we can achieve it even much better leveraging modules DB as it includes slug mappings from all official modules to their npm package name such as `image` but also popular community ones such as `nuxt module add tailwindcss`

**Comment by Atinux** [comment]
Even better!
