### ISSUE TITLE
Error: Failed to download template from registry: fetch failed

### ISSUE THREAD

**Issue by GuoJikun** [nuxt/cli#198]
`npx nuxi init my-app` is not work.

win11 22631.2338
npm 9.6.7
nodejs 18.17.1

**Comment by pi0** [comment]
Hi. Would be nice if you can provide a reproduction or some more info. But it is likely that you have a Netowrk/Firewall issue on your machine.

**Comment by GuoJikun** [comment]
![image](https://github.com/nuxt/cli/assets/21582741/dc8464aa-5e3f-45fb-9a65-69f69337ddff)

'npx nuxi init my_app' returns this information. Is there another way to get more error information?

**Comment by GuoJikun** [comment]
![image](https://github.com/nuxt/cli/assets/21582741/dc8464aa-5e3f-45fb-9a65-69f69337ddff)

'npx nuxi init my_app' returns this information. Is there another way to get more error information?

**Comment by GuoJikun** [comment]
> Hi. Would be nice if you can provide a reproduction or some more info. But it is likely that you have a Netowrk/Firewall issue on your machine.

Where is the 'nuxi init' template stored? When I use the proxy tool, it still displays Error: Failed to download template from registry: fetch failed.
![image](https://github.com/nuxt/cli/assets/21582741/54b5b5d9-f68d-417d-9b67-b747458f3fcb)

**Comment by nobkd** [comment]
The default template is here: https://github.com/nuxt/starter

**Comment by GuoJikun** [comment]
After ipv6 DNS is configured, the download succeeds.
设置 ipv6 的 DNS 后就可以成功下载了。

**Comment by Turbotailz** [comment]
I was also having this issue when trying to follow the instructions on the [Nuxt docs](https://nuxt.com/docs/getting-started/installation#new-project). Running Node v20.8.0 with NPM v10.1.0 in WSL2.

Was able to get it working by globally installing nuxi then running the command without npx.

```bash
npm i -g nuxi
nuxi init <project name>
```

**Comment by carl2049** [comment]
npx nuxi@latest init nuxt3-app
Error: Failed to download template from registry: fetch failed

npx create-next-app@latest
Works perfectly!

**Comment by GuoJikun** [comment]
> npx nuxi@latest init nuxt3-app Error: Failed to download template from registry: fetch failed
> 
> npx create-next-app@latest Works perfectly!

thanks，I successfully initialized the next project with a custom nuxt template link.
