### ISSUE TITLE
[nuxi][pnpm] nuxi module add error due to package manager conflict

### ISSUE THREAD

**Issue by angelhdzmultimedia** [nuxt/cli#215]
I used pnpm to add a new module `pnpx nuxi@latest module add @pinia/nuxt`, and I got error `Usage Error: This project is configured to use yarn`. ` ERROR  Command failed with exit code 1: corepack pnpm add -D @pinia/nuxt@latest `.

The module was successfully added to the modules array in nuxt.config.ts, but it wasn't installed due to the package manager conflict.

The project has a pnpm-lock.yaml and the deps were installed with `pnpm install` and the project created with `pnpx nuxi@latest init <name>`, and finally executed `pnpx nuxi@latest upgrade --force`.

**Comment by pi0** [comment]
Could it be possible you were previously using yarn or tried to install with an older version of cli? Is it still reproducible?

**Comment by angelhdzmultimedia** [comment]
> Could it be possible you were previously using yarn or tried to install with an older version of cli? Is it still reproducible?

Thanks for replying. I just removed Yarn from Windows 11, reloaded VSCode. Same error.

(got sure Yarn is not available)
![image](https://github.com/nuxt/cli/assets/10191085/8edcdcc5-3dbb-4ff6-a943-d7e96f94c9a2)

More info:

Even though I had Yarn installed, I never use it, so I can't understand why I get an error regarding a package manager that I don't use, and didn't use to install the deps of this project. 🤔

**Comment by angelhdzmultimedia** [comment]
### Update

Created a new project in the root of the issued project with `pnpx nuxi@latest init <name>`.
I get the same error:

![image](https://github.com/nuxt/cli/assets/10191085/97a6008d-743c-41cf-a192-608df756170e)

![image](https://github.com/nuxt/cli/assets/10191085/41c7ae7f-eade-46d9-9f34-3c0eea1ca3b0)

**Comment by angelhdzmultimedia** [comment]
### Update 2

Closed EVERYTHING. Created a new project, in the root directory of all my TypeScript projects called `test-nuxt` with `pnpx nuxi@latest init text-nuxt`.

Then `pnpx nuxi@latest upgrade --force`.

Finally, `pnpx nuxi@latest module add @pinia/nuxt`, and yarn error again...

**Comment by angelhdzmultimedia** [comment]
It's odd, because nuxi is successfully detecting my package manager choice (pnpm). Look at the scripts!
![image](https://github.com/nuxt/cli/assets/10191085/ad8e310f-890d-4eb2-9f28-c05ad5714a5f)


And this is the new project I just made after opening the issue (TypeScript/projects/test-nuxt) to rule out some weird left overs on my original project (TypeScript/projects/measure).

**Comment by pi0** [comment]
It is likely that you have a `yarn.lock` somewhere in your home folder or upper-level directories. Would it still happen if you add `"packageManager": "pnpm@8.7.6",` to your `package.json`?

**Comment by pi0** [comment]
Thanks for info. Yes there are two (unrelated) issues we are also aware of one with sibling upper `node_modules` (mlly) and one with this wrongly auto detection (nypm).

**Comment by angelhdzmultimedia** [comment]
> Thanks for info. Yes there are two (unrelated) issues we are also aware of one with sibling upper `node_modules` (mlly) and one with this wrongly auto detection (nypm).

Thank you very much for your time, energy, and information provided. Have a nice rest of the day! ☺️🤝🔥💚
