### ISSUE TITLE
Runtime module mismatch version of installed npm package

### ISSUE THREAD

**Issue by LeonardoRick** [nuxt/cli#240]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.6.2`
- Nitro Version:    `2.5.2`
- Package Manager:  `npm@9.7.1`
- Builder:          `vite`
- User Config:      `devtools`, `modules`
- Runtime Modules:  `@nuxtjs/i18n@7.3.1`
- Build Modules:    `-`

### Reproduction

https://github.com/LeonardoRick/temp-nuxt-bug

Steps to reproduce: 

1. Clone the project and set node version to `18`
2. Comment `"@nuxtjs/i18n"` inside `nuxt.config.ts` modules definition (otherwise I couldn't even run `npm install` without an error)
```javascript
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: [
    // "@nuxtjs/i18n"
  ]
})
```

3. Run `npm i `
4. Uncomment `"@nuxtjs/i18n"` insode `nuxt.config.ts`
5. Run `npx nuxi info`
6. Run `npm ls`

### Describe the bug

```
npm ls                
nuxt-app@ /Users/leonardorick/Documents/cre8tive/git/leonardorick/temp-nuxt-bug
├── @nuxt/devtools@0.6.7
├── @nuxtjs/i18n@8.0.0-beta.13
├── @types/node@18.16.19
└── nuxt@3.6.2
```
My `npm ls` shows the right version of `@nuxtjs/i18n` (`8.0.0-beta.13`) but `nuxt` seems to not recognize it properly since it's showing the wrong version on `npx nuxi info` (`7.3.1`)

This is causing my application to not being able to start.

I already tried running `rm -rf node_modules package-lock.json && npx nuxi cleanup` and as [this thread](https://github.com/nuxt-modules/i18n/issues/2213) implies, this seems not to be a `i18n` problem in this case.

Am I missing something?

**Comment by IvanWala** [comment]
Hi @LeonardoRick I just reinstall in clean mode all my dependencies included i18n ( 8.0.0-rc4 ) and nuxt (3.7.3),

Now mi problem is different https://github.com/nuxt-modules/i18n/discussions/2424#discussion-5647881
