### ISSUE TITLE
HMR issue when using nuxt cli 3.9.0 (with Apache server) 

### ISSUE THREAD

**Issue by martinsjek** [nuxt/cli#241]
Before 3.9.0 version everything worked fine for at least a year, now i'm getting errors.
I'm developing on docker with Apache layer.

Here is my Apache:
`
<IfModule mod_ssl.c>
    <VirtualHost *:443>
         ServerAlias my.local.io

         SSLEngine on
         SSLCertificateFile      /etc/apache2/ssl/my.crt
         SSLCertificateKeyFile   /etc/apache2/ssl/my.key

        ProxyPass /_nuxt/hmr/ ws://docker-container:3001/
        ProxyPassReverse /_nuxt/hmr/ ws://docker-container:3001/
        RewriteEngine on
        RewriteCond %{HTTP:Upgrade} websocket [NC]
        RewriteCond %{HTTP:Connection} upgrade [NC]
        RewriteRule ^/?(.*) "ws://docker-container:3001/$1" [P,L]

        ProxyPass / http://docker-container:3000/
        ProxyPassReverse / http://docker-container:3000/
    </VirtualHost>
</IfModule>
`

Here is my nuxt config:
`
...
vite: {
    server: {
      hmr: {
        protocol: 'wss',
        port: 3001,
        clientPort: 443,
        path: 'hmr/',
      },
    },
  },
...
`

**Comment by pi0** [comment]
Hi. Please consider that now HMR is on the same port of main dev server.

**Comment by martinsjek** [comment]
Even if i change to 3000 where is 3001 I still have an error.

**Comment by pi0** [comment]
Can you please share your updated Apache config and browser error? 

I will try to replicate in a docker env..

**Comment by martinsjek** [comment]
Updated apache config:

`
<IfModule mod_ssl.c>
    <VirtualHost *:443>
         ServerAlias my.local.io

         SSLEngine on
         SSLCertificateFile      /etc/apache2/ssl/my.crt
         SSLCertificateKeyFile   /etc/apache2/ssl/my.key

        ProxyPass /_nuxt/hmr/ ws://docker-container:3000/
        ProxyPassReverse /_nuxt/hmr/ ws://docker-container:3000/
        RewriteEngine on
        RewriteCond %{HTTP:Upgrade} websocket [NC]
        RewriteCond %{HTTP:Connection} upgrade [NC]
        RewriteRule ^/?(.*) "ws://docker-container:3000/$1" [P,L]

        ProxyPass / http://docker-container:3000/
        ProxyPassReverse / http://docker-container:3000/
    </VirtualHost>
</IfModule>
`


Updated nuxt config:
`
  vite: {
    server: {
      hmr: {
        protocol: 'wss',
        port: 3000,
        clientPort: 443,
        path: 'hmr/',
      },
    },
  },
`


Error in browser:
![Screenshot_221](https://github.com/nuxt/cli/assets/36192919/8c453fb5-6831-4860-9ced-4f4b134f4a11)


Error in console:
![image](https://github.com/nuxt/cli/assets/36192919/560e5f6c-bcc1-415a-8631-77e3ff0891a2)

**Comment by pi0** [comment]
Thanks for sharing your last config. I have made a local setup inside Docker + Apache 2 + SSL with following configuration:

```apache
<VirtualHost *:443>
	SSLEngine on
	SSLCertificateFile /etc/ssl/certs/apache-selfsigned.crt
	SSLCertificateKeyFile /etc/ssl/private/apache-selfsigned.key
	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/html
	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

	ProxyPass /_nuxt/hmr/ ws://localhost:3000/
	ProxyPassReverse /_nuxt/hmr/ ws://localhost:3000/
	RewriteEngine on
	RewriteCond %{HTTP:Upgrade} websocket [NC]
	RewriteCond %{HTTP:Connection} upgrade [NC]
	RewriteRule ^/?(.*) "ws://localhost:3000/$1" [P,L]

	ProxyPass / http://localhost:3000/
	ProxyPassReverse / http://localhost:3000/
</VirtualHost>
```

<img width="1437" alt="image" src="https://github.com/nuxt/cli/assets/5158436/90e3b707-9447-4b99-b69a-d536a924b223">

---

It seems to be all working fine on my side however i still like to investigate the issue together.

Can you try removing `vite.server.hmr` configuration if set any?

Also would you hit exactly same issue when you open `docker-container:3000` address?


----
PS: Consider Nuxi today can directly serve HTTPs/Custom Cert with a full flagged reverse proxy. Also i like to know you would need Apache 2 for development

**Comment by martinsjek** [comment]
Thanks, removing vite.server from nuxt config helped. You can close this issue.
We are using Apache mainly for local domain, like my.local.domain.io

**Comment by fouteox** [comment]
Hello, your Apache server still works with hmr since version 3.12?

I now have an error, see the issue

https://github.com/nuxt/nuxt/issues/27558
