### ISSUE TITLE
Add a way to debug `_payload.json`

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/cli#257]
Hello,

In Nuxt3, all `useFetch` or `useAsyncData` push content in a `_payload` file when page is prerendered. This is cool but it's pretty easy to have some heavy payloads because of a mistake like keeping too many keys with Content.

Could be nice to introduce a new command to easily view every payload size.

**Comment by pi0** [comment]
(discussion from https://github.com/nuxt/cli/pull/258#issuecomment-1774821538, to move it to a standalone package to iterate)
