### ISSUE TITLE
`runCommand` ignores `cwd` argument on versions after 3.6

### ISSUE THREAD

**Issue by mandarini** [nuxt/cli#274]
Here is my reproduction repository: https://github.com/mandarini/nuxi-bug

Using `"nuxi": "^3.9.1"` and `runCommand("dev", ["my-nuxt-app"])`, `runCommand` ignores the name of the project (the directory), and runs the command in the root directory.

I would expect this to work exactly like running:
```
npx nuxi dev my-nuxt-app
```

If you run the above command, you will see that it works as expected.

If you run
```
npx tsx run-nuxt.ts
```
you will see that it does not pick up the directory, and runs the command in the root directory, it shows the default Nuxt template, instead of "Hello from Katerina".

More info in the README of my reproduction repository.

[At Nx we will be using version `3.6.5`](https://github.com/nrwl/nx/pull/19855/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R230), which is before `citty` was introduced. Same version is used by `@nxext/nuxt` plugin.

I think that there's an issue with `citty` losing some arguments in this case. But maybe I am wrong.

**Comment by pi0** [comment]
Resolved in `nuxi-nightly` and next release.

**Comment by mandarini** [comment]
Wow THANK YOU!

**Comment by mandarini** [comment]
@pi0 

when I use `--no-fork` I get the following error:

```
Nuxt 3.8.0 with Nitro 2.7.2

  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

[1:20:17 PM]   ➜ DevTools: press Shift + Option + D in the browser (v1.0.0)


[1:20:18 PM]  ERROR  __name is not defined


[1:20:19 PM]  ERROR  __name is not defined (x2)


[1:20:19 PM]  ERROR  __name is not defined (x3)

[1:20:19 PM] ℹ Vite client warmed up in 467ms
[nitro 1:20:19 PM] ✔ Nitro built in 303 ms
^C%                                                               
```

I'll try the `nuxi-nightly` and see!

**Comment by mandarini** [comment]
@pi0 YES using `"nuxi": "npm:nuxi-nightly@latest"` works! THANKS!
