### ISSUE TITLE
Support `--preset` for build command 

### ISSUE THREAD

**Issue by pi0** [nuxt/cli#289]
Support `nuxi build --preset ...` as alternative to `SERVER_PRESET=... nuxi build` (nitro cli support `nitro build --preset` too)

**Comment by Atinux** [comment]
I think —preset makes sense for the build command honestly and it’s sexier :)

**Comment by pi0** [comment]
Yeah i like it more to be shorter might also makes sense if we introduce client integrations via same preset name

**Comment by Atinux** [comment]
Happy to implement it @pi0 ?
