### ISSUE TITLE
Warning when installing "nuxt2-only" modules

### ISSUE THREAD

**Issue by manniL** [nuxt/cli#321]
### Describe the feature

Hey 👋🏻

I was wondering if it'd be possible to introduce some warning when people try to use modules that aren't ready for Nuxt2 yet. This could improve DX and reduce frustration.

See e.g. https://github.com/nuxt/nuxt.js/issues/14942 and (possibly) nuxt/nuxt.js#14768 

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
We might use an explicit deprecation list, and also implement version constraints within CLI to guide users to update to latest compatible version of Nuxt for their modules.

**Comment by pi0** [comment]
It is checked in latest nuxi:

```
npx nuxi module add @nuxtjs/axios --cwd playground 

 WARN  The module @nuxtjs/axios is not compatible with Nuxt 3.11.0 (requires ^2.0.0)                                               5:23:16 PM


❯ Do you want to continue installing incompatible version?
○ Yes / ● No
```
