### ISSUE TITLE
Unable to get client IP or request protocol in development mode

### ISSUE THREAD

**Issue by xtance** [nuxt/cli#324]
### Environment

[2:31:36 PM] Nuxt project info:

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.13.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@8.19.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Nuxt project with  a middleware and a plugin, both failing to get a client IP:
https://github.com/xtance/nuxt-app-ip/

As compared to the blank h3 app:
https://github.com/xtance/h3-app-ip

### Describe the bug

I'm trying to get client IP address from an event and it couldn't show it. The only way is to read `x-forwarded-for` header and there it's always 127.0.0.1

```
export default defineNuxtRouteMiddleware((to, from) => {
    const nuxt = useNuxtApp();
    const event = useRequestEvent(nuxt);
    console.log(
        'IP',
        event.context.clientAddress,
        event.node.req.connection.remoteAddress,
        event.node.req.socket.remoteAddress,
        getRequestIP(event),
        getRequestIP(event, { xForwardedFor: true }),
    );
})
```

It returns "IP undefined undefined undefined undefined 127.0.0.1" (I also tried with a server plugin in /plugins/server)

Since I read that nuxt uses h3 I created a blank project to test it and it shows my real IP. (See in reproduction section)

### Additional context

I was wondering if I'm alone with this issue but here is a discussion: https://github.com/nuxt/nuxt/discussions/25059

**Comment by pi0** [comment]
I suspect this might be bug in nuxt CLI's proxy. Will investigate more.

In the meantime, can you also try `nuxt dev --no-fork --host 0.0.0.0`?

**Comment by xtance** [comment]
> I suspect this might be bug in nuxt CLI's proxy. Will investigate more.
> 
> In the meantime, can you also try `nuxt dev --no-fork --host 0.0.0.0`?

Adding `--no-fork` actually worked: it puts my real IP in x-forwarded-for. Other options are still undefined, but the header already works fine, thank you for your help.

(By the way, is there documentation about this command argument and what does it affect?)

**Comment by pi0** [comment]
Thanks for confirming. Using `getRequestIP` is the right way we use several internal proxies (cli, nuxt and nitro) in order to make development experience better but in situation of any reverse proxy in production also you might always need to check the headers instead of raw socket.

**Comment by pi0** [comment]
Current workaround:

- Switch to [nightly channel](https://nuxt.com/docs/guide/going-further/nightly-release-channel#opting-in) (for https://github.com/unjs/nitro/commit/29ddd948407322c67aace0336fdc65eed12bad20)
- Use `nuxi dev --no-rok`

**Comment by pi0** [comment]
fix should have been landed in latest nitro, try upgrading with `npx nuxi upgrade --force`

**Comment by c0nd3v** [comment]
@pi0 I’m getting “http” from getRequestProtocol. `nuxi dev  \-\-no-fork` fixes it.

**Comment by pi0** [comment]
@c0nd3v ~> https://github.com/nuxt/cli/issues/487
