### ISSUE TITLE
preview command failed with nitro.output.dir

### ISSUE THREAD

**Issue by xjccc** [nuxt/cli#375]
1. set `nitro.output`
```nuxt.config.ts
 output: {
    dir: 'node-server',
    publicDir: 'node-server'
  }
```
2. pnpm build
3. pnpm preview

`nitro.json` is under `node-server`, but `preview` path is `server/node-server`
```
// preview output path
[ 'Users/playground/server/node-server/nitro.json',
  'Users/playground/.output/nitro.json' ]
```

When i config `nitro.srcDir` is same output in `node-server`

**Comment by pi0** [comment]
The issue should be solved via [nightly release channel](https://nuxt.com/docs/guide/going-further/nightly-release-channel)
