### ISSUE TITLE
nuxt preview does not respect the --dotenv option

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/cli#383]
### Environment

Stackblitz

````
------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.5
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, runtimeConfig
- Runtime Modules:  -
- Build Modules:    -
------------------------------
````

### Reproduction

https://stackblitz.com/edit/nuxt-starter-qwahbu?file=package.json

### Describe the bug

I have 2 environment files `.env` and `.env.prod`. According to the docs, I can pass the `--dotenv` flag to specify a different env file to load for nuxt preview command - https://nuxt.com/docs/api/commands/preview

But it does not seem to work.

I have tried multiple variants of this and it always loads the `.env` file and not my `.env.prod` file.

Here is what I tried (see reproduction):

```diff
+ "preview": "nuxt preview --dotenv .env.prod"
+ "preview": "nuxt preview --dotenv=.env.prod"
+ "preview": "nuxt preview --dotenv prod"
```

Nothing worked.

**Comment by chrisspiegl** [comment]
I have just experienced the same (with Nuxt `3.10.3` as well as `3.11.2`).

Doc says it should work (https://nuxt.com/docs/api/commands/preview)

But my terminal even says it's just going to load `.env`

<img width="820" alt="Xnapper-2024-04-23-18 34 45" src="https://github.com/nuxt/cli/assets/1096384/1229152e-542f-4c8e-bcdc-73f5f35006b8">

I hope this helps possibly locate the issue.

**Comment by dixhuit** [comment]
Been going mad experiencing the exact same issue.

**Comment by igoohd** [comment]
Same problem here, any updates?

**Comment by manniL** [comment]
As a workaround, read in the .env variables **as you'd have to** on the server 👍🏻

**Comment by dixhuit** [comment]
https://github.com/nuxt/cli/commit/3fe1ff93bb6b943fc9621973b748a8328345c84c only appears to fix the console message, which is great, but doesn't address the reported issue (`nuxt preview` does not respect the `--dotenv` option ). Can we re-open this?

**Comment by danielroe** [comment]
Would you provide a reproduction of it not working? It works fine for me.

**Comment by dixhuit** [comment]
Ah, the original stackblitz repro is also working for me (first time trying it I'll admit). Hmm, need to double check my local project now...

**Comment by dixhuit** [comment]
Yep, not sure where the confusion stems from but my local project is behaving as expected now. Apologies for the noise.
