### ISSUE TITLE
install module peer-dependencies

### ISSUE THREAD

**Issue by danielroe** [nuxt/cli#385]
when installing modules it can be common for them to have another dependency that needs to be installed. rather than requiring this to be installed separately, it would be nice for modules in nuxt/modules to specify any additional packages that have to be installed

**Comment by pi0** [comment]
If modules expect them as peer, maybe we can ensure via an nypm to install peer deps? (npm does but it is implicit behavior)

**Comment by danielroe** [comment]
Nice idea! Ensure standards are respected 🙌
