### ISSUE TITLE
Analyze command should show descriptive file names

### ISSUE THREAD

**Issue by manniL** [nuxt/cli#390]
Hey! After https://github.com/nuxt/nuxt/pull/26203 landed, `nuxi analyze` suffers from less clear file names. As a workaround, I commonly add a snippet to remove the hash fully and use the name only (`[name].js`). It'd be great if analyze could do that by default for us though.

**Comment by MickL** [comment]
Unfortunately analyze is kinda useless a the moment because of the hashed file names.

@manniL May you share your snippet?

**Comment by BobbieGoede** [comment]
@MickL 
Here's the blogpost for v3.11 that describes how to configure the chunk filename patterns: https://nuxt.com/blog/v3-11#chunk-naming

But I'll open a PR to disable the filename hashing by default for `analyze` 😎

**Comment by MickL** [comment]
> But I'll open a PR to disable the filename hashing (or atleast prepend with filename) by default for `analyze` 😎

This sounds amazing!
