### ISSUE TITLE
Allow to pass host und port arguments for `--inspect` for `nuxi dev`

### ISSUE THREAD

**Issue by cheindl** [nuxt/cli#403]
Hello everybody,

as we are developing most of the times within docker containers, we are often not able to debug nuxt process correctly. When running `nuxi dev --inspect` the debugging port is opened, but on localhost:9229 which cannot be exposed in a container environment.

Thus it would be very helpful, to allow to pass host and port for the `--inspect` argument, e.g. the following:

`nuxi dev --inspect=0.0.0.0.1234`

The `--inspect=0.0.0.0:1234` should be properly passed as to the node process.

**Comment by filiphazardous** [comment]
I agree. There's a blog post about this use-case here:
https://www.liip.ch/en/blog/nuxt3-node-debugging

(Would a patch be welcome?)

**Comment by finfa** [comment]
Would be nice to use Nuxt with Docker and Kubernetes.
