### ISSUE TITLE
ERROR  (node:52837) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated

### ISSUE THREAD

**Issue by pochat** [nuxt/cli#405]
### Environment

- Operating System: `Darwin`
- Node Version:     `v22.0.0`
- Nuxt Version:     `3.11.2`
- CLI Version:      `3.11.1`
- Nitro Version:    `2.9.6`
- Package Manager:  `npm@10.6.0`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

-Install latest node
-Install latest nuxt
-npm run dev

### Describe the bug

When upgrading to the latest node and the lastest nuxt version,  the following error repeatedly appears in the console:
 ERROR  (node:52865) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated

The error is present at every npm run dev, and npm run build.

**Comment by danielroe** [comment]
This is an upstream issue (https://github.com/wooorm/import-meta-resolve/issues/27) which is resolved in v4.1.0 of `import-meta-resolve`, but because `nuxi` inlines `mlly`, and `mlly` inline `import-meta-resolve`, it may take a little while for the fix to percolate downward into Nuxt.

cc: @pi0

**Comment by pi0** [comment]
wroking on mlly release expect it shortly :)

**Comment by igalklebanov** [comment]
@pi0 thank you! 💪 

can we get a bump @ https://github.com/unjs/pkg-types ? still uses 1.6.1.

**Comment by manniL** [comment]
> @pi0 thank you! 💪
> 
> can we get a bump @ [unjs/pkg-types](https://github.com/unjs/pkg-types) ? still uses 1.6.1.

refreshing the lockfile should be enough there as it uses `^1.6.1`

**Comment by HummingMind** [comment]
@danielroe @manniL 

So, is this going to be fixed in CLI v3.12.0 tomorrow? Sounds like mlly was updated to use the latest version of import-meta-resolve, which has the fix for this.

Thank you for all your hard work!

**Comment by pochat** [comment]
Hi @danielroe,

I hope you are well, and thank you for the update.

I still see the error in my console. Do we need to update to the latest Nuxt version?

Thank you.

<img width="703" alt="image" src="https://github.com/nuxt/cli/assets/48400262/947ed936-5af0-454a-bdbb-1b7b12ef3780">

**Comment by danielroe** [comment]
Yes, `mlly` is used in Nuxt as well so you need to update more than just `nuxi`.

**Comment by scshasha** [comment]
> use node version v19.2.0 can clear this error info

This worked for me. Thanks @pi0

**Comment by Chambo015** [comment]
install `nvm` and use 20.15.1 version node
