### ISSUE TITLE
The nuxi preview command does not work with the custom nitro.output setting

### ISSUE THREAD

**Issue by alSergey** [nuxt/cli#418]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.13.0`
- Nuxt Version:     `3.11.2`
- CLI Version:      `3.11.1`
- Nitro Version:    `2.9.6`
- Package Manager:  `npm@10.5.2`
- Builder:          `-`
- User Config:      `devtools`, `nitro`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

1) `git clone git@github.com:alSergey/nuxi-start-repro.git`
2) Run command `npm run build_and_start`

### Describe the bug

The nuxi preview command doesn't run because it expects an .output folder. As I understand it, the problem is in this lines https://github.com/nuxt/cli/blob/b9868fedcb4545b9f84372005801ba86d4ff1b46/src/commands/preview.ts#L44-L54

### Logs

```shell-script
> nuxt preview

 ERROR  Cannot find nitro.json. Did you run nuxi build first? Search path:                                                                                                                                  20:12:34
 [ '/Users/seralekhin/Desktop/nuxi-start-repro/server/dist/nitro.json',
  '/Users/seralekhin/Desktop/nuxi-start-repro/.output/nitro.json' ]
```

**Comment by alSergey** [comment]
Hello, could you please tell me the status of this issue?

**Comment by Neemsigo** [comment]
Have the same problem. Looks like the `.output` dir is hardcoded. Can't use preview|start command with custom output dir name now :(
Do you have plans for fix this?

**Comment by pi0** [comment]
Hi. The issue should be solved via [nightly release channel](https://nuxt.com/docs/guide/going-further/nightly-release-channel). (#376)
