### ISSUE TITLE
Nuxi v3.12.0 constant pinging to localhost and failing

### ISSUE THREAD

**Issue by frasza** [nuxt/cli#432]
------------------------------
- Operating System: Windows_NT
- Node Version:     v20.14.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.7.0
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

Reproduction:
https://github.com/frasza/nuxi-issue

There seems to be an issue with Nuxi version `3.12.0` and using Nuxt version `3.11.2`.
Whever I startup dev server with `npm run dev`, it starts pinging localhost and failing.

![image](https://github.com/nuxt/cli/assets/22049682/2cfe4284-66c7-4fdf-b557-edb0adba894a)

I have tried to pin Nuxi to version `3.11.1`, it works with any issue or pinging.
```
"overrides": {
    "nuxt": {
      "nuxi": "3.11.1"
    }
  }
```

**Comment by TimGuendel** [comment]
Same problem here. I had to downgrade to Nuxt 3.11.2 because of regressions with the useCookie composable and this happened. This happens even when the DevTools are disabled.

**Comment by hermanndettmann** [comment]
I have the same issue since Nuxt 3.12!

**Comment by hermanndettmann** [comment]
I just found kind of a fix for now here: https://github.com/nuxt/nuxt/discussions/27779. But it feels like not really fixing the actual issue.

**Comment by Atinux** [comment]
Is it still the case with latest Nuxt version?

**Comment by TimGuendel** [comment]
> Is it still the case with latest Nuxt version?

No, it seems to be working now.

**Comment by frasza** [comment]
Correct, closing it since there is no problem with latest Nuxt version.

**Comment by liaow-ww** [comment]
it works, but my Nuxt version is 3.9.3
