### ISSUE TITLE
Cannot override the registry when running `nuxi module add xxx`

### ISSUE THREAD

**Issue by DevDengChao** [nuxt/cli#451]
I have some trouble connecting npm's default registry `https://registry.npmjs.org` when running `nuxi module add xxxx`, then I found nuxi is always using this registry instead of the registry user defined in npm config.

https://github.com/nuxt/cli/blob/bca75ab6490dfc444e3b6766ba5c47572622e2d3/src/commands/module/add.ts#L219-L221

**Comment by DevDengChao** [comment]
Suggested solution:
+ Option 1: define an env variable to allow user fetch packages from another registry: 
    ```js
     const pkg = await $fetch( 
         `${ process.env.NUXI_REGISTRY || 'https://registry.npmjs.org' }/${pkgName}/${pkgVersion}`, 
      ) 
    ```
+ Option 2: define an arg, e.g: `nuxi module add xxx --registry xxxx`
+ Option 3: load registry from npm config like other cli: 
    ```
    $ yarn config list
    yarn config v1.22.22
    info yarn config
    {
      ...
      registry: 'https://registry.yarnpkg.com',
      ...
    }
    info npm config
    {
      registry: 'https://registry.npmmirror.com/'
    }
    ```
    ```js
     const pkg = await $fetch( 
         `${ getRegistry() }/${pkgName}/${pkgVersion}`, 
      ) 
    ```

**Comment by Atinux** [comment]
Is this related to the same error as #453 ? If so would the proxy fallback work for you too?

**Comment by DevDengChao** [comment]
> Is this related to the same error as #453 ? If so would the proxy fallback work for you too?

Yes, they are the same issue.
