### ISSUE TITLE
ERROR Error: Failed to installing nuxt : Invalid URL

### ISSUE THREAD

**Issue by kiarashmankouei** [nuxt/cli#452]
Init new project using Nuxi.

`npx nuxi@latest init `

when i use
npx nuxi init nuxt

get me this error how can fix it
![Screenshot 2024-07-24 172214](https://github.com/user-attachments/assets/269b5719-b9fb-425c-83ca-f01a81d77df4)

![Screenshot 2024-07-24 175742](https://github.com/user-attachments/assets/687d47d9-804e-47ef-aa86-9f013983b69f)

**Comment by N-index** [comment]
nuxi@3.11.0 works well

**Comment by kiarashmankouei** [comment]
> nuxi@3.11.0 works well

thanks thats help me

**Comment by kiarashmankouei** [comment]
if anyone have this problem just use this code in your terminal that would helps you. 
npx nuxi@3.11.0  init <your project name>

**Comment by h6s8n** [comment]
Is this a temporary solution or will it be fixed in the future?

**Comment by h6s8n** [comment]
If you're encountering the following error when initializing a new project with nuxi:


`npx nuxi@latest init <project_name>`
and the error looks similar to:


**ERROR Invalid URL**
The issue might be related to proxy settings in your environment. Here's how you can resolve it:

Steps to Fix:
Check Existing Proxy Settings
Run the following command in your terminal (PowerShell for Windows):


`Get-ChildItem Env: | Where-Object { $_.Name -like "*proxy*" }`
If you see something like this:


```
Name                           Value
----                           -----
http_proxy                     127.0.0.1:10809
```
It means your environment is configured to use a proxy.

Disable Proxy Temporarily
To test if the proxy is causing the issue, temporarily disable it:


```
$Env:http_proxy=""
$Env:https_proxy=""
```
Then rerun the npx command:



Test Again
After performing the above steps, try running:

`npx nuxi@latest init <project_name>`
