### ISSUE TITLE
`Nuxi init -t` 404s on `nuxt.json`

### ISSUE THREAD

**Issue by davidjbradshaw** [nuxt/cli#456]
When I run `nuxi init -t` it fails as follows. 

```bash
 % npx nuxi init -t my-project
Need to install the following packages:
nuxi@3.12.0
Ok to proceed? (y) 


[11:22:43 AM]  ERROR  Error: Failed to download template from registry: Failed to download nuxt template info 
from https://raw.githubusercontent.com/nuxt/starter/templates/templates/nuxt.json: 404 Not Found
```

Looking at the template it indeed does not contain the file that fails to be found here.

**Comment by kiarashmankouei** [comment]
hi please use npx nuxi info to have version of node and nuxt .

**Comment by kiarashmankouei** [comment]
i use nuxi 3.11 and works for me try " npx nuxi@3.11.0 init ".

**Comment by Jos620** [comment]
Same problem here.

`npx nuxi info` outputs:

```
- Operating System: `Darwin`
- Node Version:     `v18.20.3`
- Nuxt Version:     `-`
- CLI Version:      `3.13.1`
- Nitro Version:    `-`
- Package Manager:  `unknown`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

Running with version 3.11 didn't work as well.

**Comment by danielroe** [comment]
`-t` is meant to point to the path of a template (for example, on github, with something like `-t gh:danielroe/template`).

In your case, just run `npx nuxi init my-project`

**Comment by danielroe** [comment]
try npx nuxi@latest init nuxt-app

**Comment by Jos620** [comment]
`npx nuxi@latest init nuxt-app ` raises the same error.

I thought it was some network issue in my machine, but running:

```bash
node -e "fetch('https://raw.githubusercontent.com/nuxt/starter/templates/templates/v3.json').then(r => r.json()).then(console.log)"
```

Seem to find this:

```json
{
  "name": "v3",
  "defaultDir": "nuxt-app",
  "url": "https://nuxt.com",
  "tar": "https://codeload.github.com/nuxt/starter/tar.gz/refs/heads/v3"
}
```

**Comment by Jos620** [comment]
@danielroe I tested today with version `3.15.0`, and the problem is still there. Can we reopen the issue?
