### ISSUE TITLE
Cannot find any route matching /. after setting app.baseURL to '/somepath/'

### ISSUE THREAD

**Issue by Garfill** [nuxt/cli#469]
### Environment

`npx nuxi info`

### Reproduction

1. Set app.baseURL to  '/somepath/'
2. Start app `nuxt dev -o`
3. The browser will display a 404 page which tell me Cannot find any route matching /. And the location url  is `http://localhost:3000/somepath/`
4. But after refreshing with F5, the app work correctly and show the right page.

### Describe the bug

1. Set app.baseURL to  '/somepath/'
2. Start app `nuxt dev -o`
3. The browser will display a 404 page which tell me Cannot find any route matching /. And the location url  is `http://localhost:3000/somepath/`
4. But after refreshing with F5, the app work correctly and show the right page.

**Comment by bvallier** [comment]
Would love a resolution here as well!
