### ISSUE TITLE
`module add` in 3.14.0 tries to fetch package through npm.pkg.github.com

### ISSUE THREAD

**Issue by tkjaergaard** [nuxt/cli#498]
Running for example `npx nuxi@latest module add shadcn-nuxt`

Gives an error because it tries to resolve the package through npm.pkg.github.com:

```
 ERROR  [GET] "https://npm.pkg.github.com//shadcn-nuxt/latest": 403 Forbidden   
```

Running `npx nuxi@3.13.2 module add shadcn-nuxt`  works as expected.

- Operating System: Darwin
- Node Version:     v20.16.0
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.7.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

**Comment by SwartZCoding** [comment]
Same issue. If you know how to fix this :), i want !

**Comment by manniL** [comment]
Let's track in https://github.com/nuxt/cli/issues/510#issuecomment-2414056318
