### ISSUE TITLE
Nuxi add command not working with private repositories where auth is required

### ISSUE THREAD

**Issue by gapipro** [nuxt/cli#518]
Normal usage of nuxi is via: `npx nuxi@latest module add ui`

`add` command reads custom registry setting from `.npmrc` file but it reads just the URL. Not the _auth settings that should also be taken into consideration when creating a fetch request by appending correct headers.

`.npmrc` example:

```
registry=https://<repo-path>/
//<repo-path>:_authToken="<token>"
```

There are also other properties that can be set in .npmrc file. Example of implementation: https://github.com/pnpm/pnpm/pull/8207

**Comment by jmescode-te** [comment]
Having the same issue here, and `--skipInstall` which I'm told should work when I do `npx nuxi module add --help`, does not skip the install.

**Comment by JessicaSachs** [comment]
Yeah, they symptom I have is that the private registry throws a 404 when nuxi attempts to fetch it.

![Image](https://github.com/user-attachments/assets/65291b2b-b54d-42a7-bac9-74c958ec6535)

`npm view` is able to properly resolve the disparate registries and determine which scope applies to which registry.

![Image](https://github.com/user-attachments/assets/896550c5-dbb9-44d3-9b7c-7d9e7e7ec6c1)

I have zero ideas on how to solve this legitimately, but the workaround for me was to stop using the private registry (`mv ~/.npmrc ~/.npmrc-tmp`), run my install, and then move it back.
