### ISSUE TITLE
Option for pure JavaScript mode in new and existing projects?

### ISSUE THREAD

**Issue by gowy222** [nuxt/cli#556]
### Describe the feature

Hello Nuxt team,

I appreciate the powerful features and flexibility Nuxt provides. However, I've encountered a challenge when trying to use Nuxt with pure JavaScript, both for new projects and when integrating Nuxt into existing Vue.js projects.

Current situation:
1. When initializing a new project with `pnpm dlx nuxi@latest init <project-name>`, all generated files are in TypeScript.
2. There's no clear option to choose a pure JavaScript setup during project initialization.
3. Integrating Nuxt into existing Vue.js projects that use JavaScript (not TypeScript) is challenging.

Feature request:
1. Add an option during project initialization to choose between TypeScript and JavaScript setups.
2. Provide a clear guide or command to convert an existing Nuxt TypeScript project to pure JavaScript.
3. Offer documentation on how to integrate Nuxt into existing JavaScript-based Vue.js projects without requiring a full migration to TypeScript.

Thank you

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
There's no plan to do so. But you can create and use your own template that's perfectly customised for your use case. For example, you can pass a github repo like this: `npx nuxi init -t gh:yourorg/yourrepo nuxt-app`.
