### ISSUE TITLE
`nuxt devtools enable|disable` works only with `--command` flag

### ISSUE THREAD

**Issue by AndreyYolkin** [nuxt/cli#69]
## Problem
According to the [docs](https://nuxt.com/docs/api/commands/devtools), users can just type `nuxi devtools enable` to enable devtools in the project. Howerver, after https://github.com/nuxt/cli/pull/47 enable/disable flag can only be submitted with `--command` before the value.

There I need to ask: which way is preferred for the future? Should we change documentation or fix the command itself?

### 2. There I logged `ctx.args`:
<img width="545" alt="image" src="https://github.com/nuxt/cli/assets/11289484/3b5a4296-fc55-446b-8b66-0de888232e4f">

### 3. There is the run without `--command` flag, as documented:
<img width="949" alt="image" src="https://github.com/nuxt/cli/assets/11289484/56e27f63-c339-4e33-9477-3773401f03df">

### 4. There is the run with `--command flag`:
<img width="798" alt="image" src="https://github.com/nuxt/cli/assets/11289484/1ed749df-93cf-4f7f-8d99-8a26f8cc9ddd">

**Comment by dycops** [comment]
![webstorm64_gItssxBJIR copy](https://github.com/nuxt/cli/assets/38084056/e617ab0c-7a4a-4a00-8602-56f6024d5f04)
Have the same error

**Comment by Hebilicious** [comment]
@danielroe should we update the docs to use --command, or change this behaviour ?

**Comment by danielroe** [comment]
I think we should fix the behaviour here.
